### ISSUE TITLE
Scala 2.x cross-build for Specs2 5.0

### ISSUE THREAD

**Issue by djspiewak** [etorreborre/specs2#1007]
I come bringing gifts of maintenance hell! :-)

The current approach where Specs2 4.x is Scala 2 only, while Specs2 5.x is Scala 3 only, is… really really difficult for the ecosystem. It's not so much a problem for *direct* users (i.e. folks who are using an `% Test` dependency, though there are challenges there as well), but it's *very* difficult for anyone who is building on top of Specs2 as an intermediary library. discipline-specs2 and cats-effect-testing are the two which immediately come to mind.

The problem is that the cross-version suffixes on both the direct and indirect dependencies start to conflict, and you very quickly land in situations where downstream users need to add excludes in order to make any meaningful progress. The fact that Specs2 depends on macrotask executor (even for its JVM artifacts), which is cross-published, while not actually cross-publishing is part of what creates some of this mess. Projects like Cats Effect which *also* depend on macrotask executor then land in a bit of a bind, where they need to explicitly exclude the non-matching cross-publication of macrotask in order to avoid conflicts. You can see the madness this creates by looking at the Cats Effect build.

And that's even *before* we get into the issues of Specs2 4.x vs 5.x, which are not mutually source or binary compatible. Intermediate libraries like cats-effect-testing which want to support Scala 2 and Scala 3 in a source-compatible way are held over a very unpleasant barrel, where they must either *not* support Specs2 4.x, or not support Specs2 5.x, or must pass on a situation which creates dependency hell for their downstream users (since the Scala 2 -> 3 upgrade would then require also upgrading Specs2 versions and materially changing sources). This is the worst sort of yak shaving.

The only meaningful solution here is to cross-publish one or both of Specs2 4.x or 5.x, at the *very* least for 2.13 and 3.0. I realize that's a huge ask, but without something like that, the downstream ecosystem is going to be in dependency and upgrade hell for the next few years (until the majority of the world is forward to Scala 3).

**Comment by armanbilge** [comment]
Out of curiosity, is specs2-5 on 2.13 more viable than (at least some of) specs2-4 on 3? Without knowing anything, I would guess the former is harder (since specs2-5 is using Scala 3 syntax which would have be dialed back). And furthermore without specs2-5 on 2.12 e.g. CE3 still doesn't have an upgrade path while it's still cross-compiling for 2.12. But, I wouldn't know :)

**Comment by armanbilge** [comment]
@etorreborre not exactly the same, but here are Daniel's thoughts on dropping the 2.12 cross-build from circe:
https://github.com/circe/circe/pull/1818#issuecomment-909397865

**Comment by djspiewak** [comment]
I think the Circe comment mostly sums up my thoughts. :-) So the problem with these kinds of migrations always comes down to the fact that there are so many moving parts. The ideal thing from the perspective of the *user* is to be allowed to shave just one part of the yak at a time. This generally makes it a lot easier since, not only can the task be delivered more incrementally, it also ensures that any problems which are inevitably encountered along the way are known to stem from a single change, as opposed to one of many changes (or perhaps even the interaction between many changes, which is even worse).

For this reason, I think it's really ideal if libraries in general provide a source-compatible (as much as possible) cross-build between Scala 2 and Scala 3 in a particular version (whatever version is appropriate), and then in the *next* version move to Scala 3 only if so desired.

**Comment by etorreborre** [comment]
@djspiewak here is a version that is compatible with `2.12`, `2.13` and `3.1`: https://repo1.maven.org/maven2/org/specs2/specs2-core_3/4.14.1-cross. It is a temporary solution since I had to remove some features supported by macros (auto-examples for immutable specifications). 

Additionally:

 - expectations must be expressed as `value must matcher` or `value must not(matcher)`, and avoid expressions like `a must not be something`. This is in line with specs2 5.x.
 - type inference with some matchers (like `beLike` or `contain`) might require some annotations
 - implicit resolution can have some slight differences in behaviour
 
 Please tell me if this version works for you or if there are any hiccups (and sorry for the delay, it's been 5 months!)

**Comment by armanbilge** [comment]
@etorreborre that's fantastic! discipline-specs2 builds ok against it. @vasilmkd can cut us a snapshot, and then we can give it a try in CE3 :)

- https://github.com/typelevel/discipline-specs2/pull/346

**Comment by djspiewak** [comment]
Hoooooooly crap that's cool.

**Comment by armanbilge** [comment]
I opened a PR including trying this in Cats Effect. I ran the `IOSpec` locally on both 2.13 and 3 and seems to be working very nicely!
- https://github.com/typelevel/cats-effect/pull/2908

**Comment by etorreborre** [comment]
Thanks for the feedback! I'm glad that it seems to be working, at least for cats-effect. I wonder when we will eventually switch to 3.x builds only (for cats-xxx). (I have no clue but here is a foolish bet: it will be mid-2024).

I'm closing this issue for now, please reopen if there's a problem
