### ISSUE TITLE
Questions about specs2 version 4.13.0

### ISSUE THREAD

**Issue by mkurz** [etorreborre/specs2#1022]
Hi,

I saw you released specs 4.13: https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.13.0/
Is it safe to use that version or should we stay on 4.12.x?
It seems like it was cut from the `specs2-cross` branch? (See https://github.com/etorreborre/specs2/commits/specs2-cross)
So what is the plan with 4.13? It looks like you try to cross build against Scala 2.12.x, 2.13.x and 3.x? Is that correct?
Thanks!

**Comment by etorreborre** [comment]
`4.13.0` was actually published from the [`specs2-4.x-maintenance` branch](https://github.com/etorreborre/specs2/tree/specs2-4.x-maintenance). So it is indeed the latest version in the 4.x series.

The `specs2-cross` branch is an attempt to provide a subset of specs2 (with no macros used for the implementation for example) in order to provide a temporary "bridge" between Scala2 and Scala3 before people are ready to use specs2-5 which is Scala3 only. I still have some work to do on that branch. For now specs2-core is compiling but some tests are not passing and I need to fix them.

**Comment by mkurz** [comment]
:+1: Thanks for the explanation!
