### ISSUE TITLE
Scala 2.11 support possible?

### ISSUE THREAD

**Issue by hsn10** [etorreborre/specs2#1113]
Its possible to add back Scala 2.11 support which will make Scala version support in spec2 to be on par with scalatest?

My libraries are currently using scalatest:

crossScalaVersions := Seq("2.12.17", "2.11.12", "2.13.10", "3.1.3"),
libraryDependencies += "org.scalatest" %%% "scalatest" % "3.2.14" % "test"

we imported new scala library into ecosystem we maintain which is using specs2 and need to bring scala version support to same level as rest. 

Can you add Scala 2.11 support back if possible to do it easily just by adding to crossScalaVersion in specs2 or we need to migrate current test code to scalatest?

**Comment by etorreborre** [comment]
Hi, I had a look at this and it is not a trivial change to support 2.11. It would not be _impossible_ but this would make my life even harder since I currently have to maintain a full 2.12/13 version, a limited 2 / 3 version and a full 3 version... If it is not too hard to migrate those tests to scalatest you might as well do it and get something consistent for your codebase.

**Comment by etorreborre** [comment]
I am closing this issue as "won't fix" but you can try to use [the latest specs2 version for Scala 2.11](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.11/4.10.6/), and the same version for [2.12](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.12/4.10.6/) and [2.13](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.10.6/) + a close version for [3.0](https://repo1.maven.org/maven2/org/specs2/specs2-core_3/4.15.0/). This will require some tweaking in sbt in order to specify different specs2 versions per scala version but this might work.
