### ISSUE TITLE
4.x series status?

### ISSUE THREAD

**Issue by george-wilson-rea** [etorreborre/specs2#1117]
Hi Eric, thanks for specs2.

I notice that 4.18.0 has recently been released, without a build for Scala 3. Does this mean that from now on the 4.x series is for Scala 2 and 5.x is for Scala 3? If not, would it be possible to release 4.18 for Scala 3?

**Comment by etorreborre** [comment]
Hi George,

The situation is the following:

 1. there is a 4.x series for Scala 2 with all the original features
 2. there is a 4.x-cross series for both Scala 2 and 3 with less features (in particular some things related to macros)
 3. there is a 5.x series for Scala 3 with all the original features (possibly not fully backwards compatible here and there, for example due to some difference in implicit resolution when switching to `given` and `Conversion`)

My wish would be that everyone eventually migrates to Scala 3 and I just have one branch to maintain but we all know that this can take a very long time :-).

Now about 4.18, that release was actually a mistake on my side and is going to be reverted (see #1116).

**Comment by george-wilson-rea** [comment]
Hi Erik, is what you've described here still the plan? It looks to me like `4.x` has started supporting Scalas 2 and 3, and `4.x-cross` releases have stopped?

**Comment by etorreborre** [comment]
I am sorry, the whole thing is complicated to describe. If you are only using the "core" modules, like `specs2-core`, `specs2-matcher`,..., then you can use them with both [Scala2](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.19.0/) and [Scala3](https://repo1.maven.org/maven2/org/specs2/specs2-core_2.13/4.19.0/). However some more exotic modules, like [specs2-gwt](https://repo1.maven.org/maven2/org/specs2/specs2-gwt_2.13/4.19.0/) are only available for Scala2.

**Comment by etorreborre** [comment]
@george-wilson-rea from what I'm reading `doobie` uses only `specs2-core` in version `4.19` on the `main` branch so everything should be working ok in both Scala2 and Scala3 if a more recent `doobie` version gets published (the last one is almost one year old).

**Comment by george-wilson-rea** [comment]
>the whole thing is complicated to describe

Your description makes senes to me. Thank you for taking the time to explain. :)
