### ISSUE TITLE
aka operator in matcher is broken

### ISSUE THREAD

**Issue by noam-almog** [etorreborre/specs2#318]
Using aka in a matcher is causing it to break and return ThrownExpectation.

```scala
class SomeTest extends SpecificationWithJUnit {

  case class SomeThing(str: String)

  def matcher(str: String): Matcher[SomeThing] = beEqualTo(str) ^^ { (_: SomeThing).str }
  def matcherWithAka(str: String): Matcher[SomeThing] = beEqualTo(str) ^^ { (_: SomeThing).str aka "str" }
  def matcherWithAkaWorkaround(str: String): Matcher[SomeThing] = beTypedEqualTo(str) ^^ { (_: SomeThing).str aka "str" }

  "Some" should {

    "test matcher" in {
      SomeThing("str") must matcher("str")
    }

    // this is failing
    "test matcher with aka" in {
      SomeThing("str") must matcherWithAka("str")
    }

    // this is passing
    "test matcher with aka workaround" in {
      SomeThing("str") must matcherWithAkaWorkaround("str")
    }
  }
}
```

If I will change the matcher inside the custom matcher to beTypedEqualTo the matcher will work.

**Comment by etorreborre** [comment]
Thanks for the reproducible test case. I'll try to have a look at that in a few days because I'm on holidays at the moment and far from my laptop.

**Comment by etorreborre** [comment]
The reason why this doesn't work is not really because of `aka` but because you are using the `beEqualTo` matcher. `beEqualTo` is equivalent to testing the "untyped equality" of 2 objects, like the `==` operator.

The `^^` operator is overloaded to accept either a `f: S => T` or `f: S => Expectable[T]`. However if `^^` is used with `beEqualTo`, it is happy to unify `T` with `Any` and accept whatever to do the comparison. If `^^` is used with `beTypedEqualTo[String]` then the second form is used and passes as expected.

**Comment by noam-almog** [comment]
@etorreborre 
I'm not sure I understand, I have two matchers:
```scala
beEqualTo(str) ^^ { (_: SomeThing).str }
beEqualTo(str) ^^ { (_: SomeThing).str aka "str" }
```
They both use the same beEqualTo and the same adapt function that returns the exact same type.
The first matcher (without the aka) is working as expected while the other one returns *org.specs2.matcher.ThrownExpectations*. the only deference is that one has aka and the other one doesn't.

**Comment by etorreborre** [comment]
Sorry, this is a bit hard to explain. `beEqualTo` returns a `Matcher[Any]`. The `^^` operator accepts a function from `S => Any` and uses the `Any` to do the comparison. So whatever the function provides, in this case an `Expectable` (the object built when you call `aka`, essentially a value and its description), this is the value used to do the comparison.

On the other hand when you use `beTypedEqualTo` you get a `Matcher[String]` and there is _another_ `^^` operator on the `Matcher` type which can be called with an `Expectable[String]` and knows how to use the encapsulated value to do the comparison. You get the right `^^` operator being called with `beTypedEqualTo` because the type inference has enough type information to do so.
