### ISSUE TITLE
Ability to force sequential spec to report after execution of all examples

### ISSUE THREAD

**Issue by prettynatty** [etorreborre/specs2#326]
It would be great to have ability to choose between reporting as soon as example have been executed and reporting after all spec's examples were executed.
My use-case is a spec with lots of debug information and it is hard to trace examples execution results if spec is sequential.

**Comment by etorreborre** [comment]
Which version are you using? Can you try 2.4.16?

**Comment by prettynatty** [comment]
I've been using 2.4.14 and it reported after all examples have been executed which was useful. After upgrading to 2.4.16 I've lost examples reports because they were mixed with debug generated by example's code.

**Comment by etorreborre** [comment]
Sorry I misread what you wrote. Indeed 2.4.14 was broken but useful in your case. This is not especially hard to implement but I need to think a bit about it:

 - is there a way to implement this with the existing functionalities?
 - otherwise, what would be a good name for an option allowing this behaviour?

**Comment by etorreborre** [comment]
I published 2.4.17-SNAPSHOT where you can pass `asap` on the command-line to execute the full specification before it is reported.

**Comment by prettynatty** [comment]
:octocat: bless @etorreborre!
