### ISSUE TITLE
Upgrade shapeless and scala 2.10 version

### ISSUE THREAD

**Issue by julien-truffaut** [etorreborre/specs2#351]
Would it be possible to upgrade shapeless to 2.10 and scala 2.10 to 2.10.5?

**Comment by etorreborre** [comment]
You mean shapeless to 2.1.0 right? Also, I need to fix the build because `specs2-core` code doesn't depend on shapeless anymore. This means that you can exclude the `shapeless` dependency coming up with `specs2-core` in your build file and thing should work fine (only the `specs2-gwt` module is using `shapeless` now).

**Comment by julien-truffaut** [comment]
yes sorry shapeless 2.1.0 but preferably using the scala 2.10.5 version than 2.10.4. Ah ok I got a conflict when I tried to upgrade shapeless

**Comment by etorreborre** [comment]
Done in 3.3.1.
