### ISSUE TITLE
Remove or modify the specs2.jar that is published to Maven for 3.0+

### ISSUE THREAD

**Issue by kflorence** [etorreborre/specs2#354]
I think it might have published improperly... when I import it, it only has `org.specs2.info` package in it, nothing else.

**Comment by kflorence** [comment]
Hm, version `3.3` has this problem as well. I'm compiling with Scala 2.10.4 (specs2_2.10).

**Comment by etorreborre** [comment]
This is to be expected. Starting from 3.0 you should only use the "small" jars: `specs2-core`, `specs2-junit` and so on, depending on the [functionalities you need](https://etorreborre.github.io/specs2/guide/SPECS2-3.3.1/org.specs2.guide.Installation.html). I need to have a look at the remaining `specs2.jar` and either remove it from the distribution or just keep it with dependencies to all the other jars so that they are downloaded when you use only that jar in your sbt project.

**Comment by kflorence** [comment]
Ah, that is good to know. Yes, the specs2 jar is still being published, but it doesn't really have anything in it :)

**Comment by etorreborre** [comment]
I have removed the `specs2` jar from publishing now. See for example [3.3.1-20150405231649-9410ef3](https://oss.sonatype.org/content/repositories/releases/org/specs2/specs2-core_2.11/3.3.1-20150405231649-9410ef3), where there is no corresponding `specs2-3.3.1-20150405231649-9410ef3` jar.
