### ISSUE TITLE
Nested Examples Bug in specs2 2.4.2 and 3.4

### ISSUE THREAD

**Issue by adamdecaf** [etorreborre/specs2#360]
Hey!
 
We're in the process of upgrading all our tests from 2.4.2 to 3.4, but we're seeing an issue. I've narrowed down the issue to [this series of test cases](https://github.com/adamdecaf/specs2-nested-examples-bug). In short I would expect the follow test to fail, but it does not.

```scala
  "A" >> {
    "B" >> {
      "C" >> {
        1 must be_==(2) // Why doesn't this fail the test?
      }
      1 must be_==(3) // Or this?
    } 
    1 must be_==(1) 
  }
```

Let me know if I can be of any help with this. Thanks!

**Comment by etorreborre** [comment]
This doesn't fail because this is not how a Specification is supposed to be written (I am not saying that this is your fault, we should find a way to avoid this to be written).

Your case is equivalent to
```scala
"A" >> {
    "B" >> {
      1 must be_==(3)
    } 
    1 must be_==(1) 
  }
```

Which in turn means
```scala
"A" >> {
    addExample("B", {1 must be_==(3)})
    1 must be_==(1) 
  }
```

And then desugared to (the actual names are different)
```scala
addExample("A", { addExample("B", {1 must be_==(3)}); 1 must be_==(1) })
```

So you eventually end up with just 1 example containing some code creating another example.
When `A` is executed a new example, `B` is being added to the specification but it is too late to consider it for execution. 

On the other hand if you declare:
```scala
"A" >> {
    "B" >> { 1 must be_==(3) } 
    "C" >> { 1 must be_==(1) }
  }
```
Then the code is desugared to
```scala
addBlock("A", { addExample("B",...); addExample("C")})
```
which is basically
```scala
addStart // start of a block
addText("A")
addExample("B",...)
addExample("C", ...)
addEnd // end of a block
```

This means that both "B" and "C" will be executed as separate examples. 

So this all works as designed but I don't know of any way yet to prevent you to write such a code (maybe I could print out a warning at the end of the execution to detect this situation?).

BTW, note that if you need to "label" some assertions in your examples you can write
```scala
"A" >> {
  "B is ok" ==> {
    1 must be_==(3)
  } 
  1 must be_==(1) 
}
```
This will print
```scala
[error] x A
[error]  B is not ok because '1' is not equal to '3'
```

And nested as in your example
```scala
"A" >> {
  "B is ok" ==> {
    "C is ok" ==> {
      1 must be_==(2) // Why doesn't this fail the test?
    }
    1 must be_==(3) // Or this?
  }
  1 must be_==(1)
}
```
This prints
```scala
[error] x A
[error]  B is not ok because C is not ok because '1' is not equal to '2'
```

**Comment by adamdecaf** [comment]
Well that's certainly interesting @etorreborre! I've usually just used one level deep of examples, so it's good to note that `==>` is needed in order to be able to nest examples. Thanks for checking into this!

**Comment by etorreborre** [comment]
>  it's good to note that `==>` is needed in order to be able to nest examples

I just want to reinforce that you are not really "nesting" examples with `==>`. You are just giving an additional meaning to an "expectation". A full-blown *Example* in specs2 is more than this because it can be selected, tagged, timed-out and so on.

As such it is not possible to "nest" examples in specs2. The mental model you need to have is one of a flat list of so-called "fragments": texts, steps, examples. Some of those fragments are executable like step and examples and some of them, examples, produce "Results".

What we do in a mutable specification with the `>>` DSL is merely create a list of Text fragments and Example fragments + some additional "formatting" fragments to indent the different blocks on the console. But there is no such thing as a "Tree" or "nesting".

I hope this clarifies and again I am sorry because I don't know yet how to prevent this sort of mistake when using the DSL.

**Comment by adamdecaf** [comment]
@etorreborre Ah alright, that helps explain what's going on. Thanks!
