### ISSUE TITLE
False should be an instance of Boolean

### ISSUE THREAD

**Issue by britishdan** [etorreborre/specs2#367]
The following test fails:

```scala
class Test extends Specification {
  "boolean" >> {
    false should beAnInstanceOf[Boolean]
  }
}
```

Unless I'm missing something, I believe that this test should pass.
Thanks.

**Comment by etorreborre** [comment]
Hi,

The failure message gives a clue
```scala
`false: java.lang.Boolean` is not an instance of `boolean`
```
So this test passes
```scala
false should beAnInstanceOf[java.lang.Boolean]
```

**Comment by nargov** [comment]
Hey,

While this is true, the following also passes:

```scala
false.isInstanceOf[Boolean] must beTrue
```

This creates somewhat of an inconsistency, but I'm not sure why.

**Comment by etorreborre** [comment]
Right, that's confusing but I don't how to fix this. The `scala.Boolean` type is tricky
```scala
/** `Boolean` (equivalent to Java's `boolean` primitive type) is a
 *  subtype of [[scala.AnyVal]]. Instances of `Boolean` are not
 *  represented by an object in the underlying runtime system.
 *
 *  There is an implicit conversion from [[scala.Boolean]] => [[scala.runtime.RichBoolean]]
 *  which provides useful non-primitive operations.
```
The `beAnInstanceOf[T]` matcher expects a `ClassTag[T]` to check if the value is assignable but the comment above says that the `scala.Boolean` type is not represented. However an operation like `isInstanceOf` are implemented for this type.

Maybe I should restrict this matcher to `AnyRef` in order to avoid this issue to occur.

**Comment by etorreborre** [comment]
From now on it will be necessary to convert a `scala.Boolean` to an `AnyRef` to use the `beAnInstanceOf` matcher. This should prevent this issue to happen.

**Comment by britishdan** [comment]
Thanks @etorreborre
