### ISSUE TITLE
containTheSameElementsAs for mockito verify

### ISSUE THREAD

**Issue by viliusl** [etorreborre/specs2#394]
Hi Eric,

Tried to use subj. matcher in mockito verify, but type did not match.

```scala
trait Collaborator {
  def call(ids: Seq[String]): Unit = {}
}
//...
    there was one(collab).call(
      containTheSameElementsAs(ids)
    )
```

gave me:
> Error:(20, 31) type mismatch;
> found   : org.specs2.matcher.Matcher[Traversable[String]]
> required: Seq[String]
> containTheSameElementsAs(ids)
> ^

whereas

```scala
    there was one(collab).call(
      containTheSameElementsAs(ids).asInstanceOf[Matcher[Seq[String]]]
    )
```

worked.

Full source: https://github.com/viliusl/specs2-issues/blob/master/src/test/scala/lt/vilius/MockitoVerifyTest.scala

Thanks

**Comment by etorreborre** [comment]
I'm not sure how to fix this. `containTheSameElementsAs` is a `Matcher[Traversable[T]]` in order to be as general as possible. However this prevents the implicit conversion transforming `Matcher[T]` into `T` when using matchers as Mockito arguments.

One way to solve this without using `asInstanceOf` is to do "adapt" the matcher:
```
   there was one(collab).call(
      containTheSameElementsAs(Seq(1)) ^^ toTraversable
    )
  def toTraversable[T] = (s: Seq[T]) => s:Traversable[T]
```

**Comment by viliusl** [comment]
Ok, got it.

Thanks.
