### ISSUE TITLE
Make ContainWithResultSeq[T] covariant

### ISSUE THREAD

**Issue by fdietze** [etorreborre/specs2#407]
This would have the advantage of using "must contain(...)" with instances where the type is different, but still correct.

Right now I have to cast explicitly.

class ContainWithResultSeq:
https://github.com/etorreborre/specs2/blob/64768716a12c4128690c2de5bf34324763c8168c/matcher/src/main/scala/org/specs2/matcher/TraversableMatchers.scala#L280

**Comment by etorreborre** [comment]
I don't think this is possible because of the signature of the `apply` method on `Matcher`. If I try to set T as covariant, then I get lots of `covariant type T occurs in invariant position in type` messages, especially on the `def apply[S <: GenTraversableOnce[T]](t: Expectable[S])` method which I can't change because it is inherited. If you have ideas for an alternative design I'm all ears.

**Comment by fdietze** [comment]
Ok, this is more difficult than I thought...
Nevermind, then I will go with the casts. Thanks for looking into it.
