### ISSUE TITLE
java.lang.Exception: Invalid ScalaCheck args: List(include, a-tag)

### ISSUE THREAD

**Issue by ArturSoler** [etorreborre/specs2#414]
In order to run just a single test, in version 3.6.3 we had a test marked with a tag. To run it, we did `ourproject/testOnly com.test.class.name -- include a-tag`.

After upgrading from 3.6.3 to 3.6.4, the same command results in the following exception:

`[error] (ourproject/test:testOnly) java.lang.Exception: Invalid ScalaCheck args: List(include, a-tag)`

**Comment by zainab-ali** [comment]
I think this issue is for all arguments passed to `testOnly`.
We have the following command:
`testOnly com.test.class.name -- html !pandoc`
After upgrading from 3.6.3 to 3.6.4, the command results in the following exception:
`[error] (ourproject/test:testOnly) java.lang.Exception: Invalid ScalaCheck args: List(html, !pandoc)`

**Comment by etorreborre** [comment]
The issue and its solution have been recently raised on the [mailing-list](https://groups.google.com/forum/#!topic/specs2-users/-nxZtadiBoI). 

You need to make sure that you are not passing specs2 arguments to the ScalaCheck framework in your sbt configuration:
```
// only pass arguments to specs2
testOptions in Test += Tests.Argument(TestFrameworks.Specs2, "include", "a-tag")
```
