### ISSUE TITLE
Filesrunner should exit with -1 if there's a least a failure 

### ISSUE THREAD

**Issue by edmondo1984** [etorreborre/specs2#437]
It is impossible to integrate the file runner with Gradle, if not

**Comment by etorreborre** [comment]
I thought I was already doing that but no :-(. I'll fix this. Does the value matter? The only thing you should expect is a value `!= 0`, right?

**Comment by edmondo1984** [comment]
Correct, I asked on the specs2 channel how to fix it but didn't get any
answer. Do you think you will release that change soon?

**Comment by etorreborre** [comment]
I'm working on it but it is getting late so it might only be for tomorrow.

**Comment by edmondo1984** [comment]
Can you when you have a second explain the fix? I was trying on how to
return the value up the stack but since it is using Action [Unit] I didn't
find an obvious way without changing the signature

**Comment by etorreborre** [comment]
I am publishing a snapshot version right now: `3.6.6-20151201104535-5471f71`. I will spend more time to review and test the fix tomorrow (the current code is on the `topic/exit-codes` branch for now).

The idea to have the `Reporter` return the `Stats` at the end of the execution and to check the `Stats` in the `Runner` to set the exit code. It is slightly more complicated than this because a `Runner` can run several specifications at once so a `List` of `Stats` is effectively collected and then folded into one summary `Stats` object. 

Then the main change in `Reporter`, to return `Action[Stats]` instead of just `Action[Unit]` is to do the following
```
val sinks = (printers.map(_.sink(env1, spec)) :+ statsStoreSink(env1, spec)).suml
val reportFold = Statistics.statisticsFold <* sinks

Actions.fromTask(reportFold.run[ProcessTask](contents))
```

In addition to the sinks I add a `statisticsFold` which is just collecting statistics on the fly. Running that composite fold has the effect of returning the `Stats` and outputing results to the screen (or whatever Sink effect, html, junit,...)

**Comment by etorreborre** [comment]
Sorry take `3.6.6-20151201123413-0e061ad` instead (should be available in a few minutes).

**Comment by etorreborre** [comment]
Hi @edmondo1984 does that work for you now?

**Comment by etorreborre** [comment]
I am assuming this works ok and closing the issue. Please re-open if that's not the case.

**Comment by edmondo1984** [comment]
sorry I didn't try yet, will try tomorrow

**Comment by etorreborre** [comment]
You can use `3.6.6-20151201123413-0e061ad` for now. I will publish a `3.7` version this weekend (targeting Scalaz-7.2.0 by default but there will also be a `3.7-scalaz-7.1.6`).
