### ISSUE TITLE
Scala.js Support?

### ISSUE THREAD

**Issue by mdedetrich** [etorreborre/specs2#465]
Apologies if this has been asked before, but is there a plan to add in support for Scala.js?

**Comment by etorreborre** [comment]
No this is something that I would like to do but I haven't touched it for now because I need 2 major dependencies to be Scala.js compatible: Scalaz and Scalaz-stream. Scalaz now has a Scala.js version but not Scalaz-stream yet. Then the next thing I need to find is more time which I might have in May if April is a bit busy.

**Comment by mdedetrich** [comment]
Cool thanks, just wanted to see if it was something thats on the radar.

**Comment by InTheNow** [comment]
See also https://github.com/functional-streams-for-scala/fs2/issues/500

**Comment by pauldraper** [comment]
This would be really, really incredible.

A workaround in the meantime is to test Scala on the JVM, even though it will be run by a JavaScript VM. The disadvantages are 
(1) It doesn't actually test on a JS runtime, and there can be differences.
(2) Tested code can't rely on JS libraries. (i.e. this only works for transitively pure-Scala projects)

**Comment by mdedetrich** [comment]
@pauldraper I have been using uTest with https://github.com/lihaoyi/utest/issues/2#issuecomment-67300735, which for basic usage works out great, but proper specs2 support would be fantastic

**Comment by dwijnand** [comment]
No more scalaz-stream, so this just got simpler..

**Comment by etorreborre** [comment]
@dwijnand yes and maybe no because I "inlined" a few scalaz-stream classes into specs2 to do that.

**Comment by dwijnand** [comment]
Yeah I saw (after).

I guess I optimistically presumed that support wasn't there yet for work-effort and/or release schedule reasons rather than for technical difficulties..

**Comment by xavier-fernandez** [comment]
`ScalaZ-stream` is discontinued, FS2 is the successor:

https://github.com/functional-streams-for-scala/fs2

**Comment by cchantep** [comment]
Hi, we have prepared a branch : https://github.com/cchantep/specs2/tree/opendays-201704

There is some issue about forking test, if anyone have idea to fix that.

**Comment by etorreborre** [comment]
Hi, I also started working on the subject:

 1. removed scalaz-stream: done
 2. removing scalaz altogether: [in progress](https://github.com/etorreborre/specs2/tree/specs2-fp-lib)
 3. creating a scala.js build: [first attempt](https://github.com/etorreborre/specs2/tree/specs2-js)

When working on 3. I realized that the execution model of specs2 was really getting in the way because we are awaiting futures in a few places and this doesn't work with JavaScript. So I kept on working on the the `specs2-fp-lib` branch to fix this. The code is mostly done but many tests are still failing. 

Once that branch is ready I plan to do a RC release. Then I want to rebase 3. on top and work until all the tests pass in both JVM and JS modes. Finally we could be ready for specs2 4.0 :-).

I think I should finish 2. now but I welcome some help for 3. (also with the change from `Build.scala` to `build.sbt`). What do you think?

**Comment by ngbinh** [comment]
this is awesome!

**Comment by etorreborre** [comment]
Finally the first spec executed with scala-js!
![image](https://user-images.githubusercontent.com/10988/27817867-84a266fe-6093-11e7-8232-f8f2483890bd.png)
There's lots of polishing and testing to be done but I hope to publish a `4.0.0-RC1` soon.

**Comment by cchantep** [comment]
Very nice @etorreborre :+1

**Comment by etorreborre** [comment]
specs2 `4.0.0-RC2` is now available for testing with scala.js and I can finally close this issue, 1 year and a half after it was opened :-)

**Comment by mdedetrich** [comment]
@etorreborre Congrats, can't wait for version 4 to come out!
