### ISSUE TITLE
"No configuration setting found for key 'akka' " error on v3.8 when using Akka ActorSystem

### ISSUE THREAD

**Issue by djriffel** [etorreborre/specs2#478]
Hello,

I had a build.sbt file with "latest.release" specified for specs2-core and specs2-mock which was working fine when on version 3.7-20160219163315-d9c5826 but then it started recently failing on newer versions when used on any tests that extended or mixed-in org.specs2.mutable.Specification/SpecificationLike whenever instantiating an ActorSystem (confirmed with both extending via TestKit(ActorSystem("foobar")) or manually instantiating in the test class body).

The error seems to be related to the Akka config not being found (I've never specified one as a parameter in the past, but upon doing some homework it seems that it gets auto-loaded from an akka default whenever left unspecified). I decided to post here instead of any akka repo because when trying a similarly old version of akka the problem still existed on the 3.8 version of specs2.

Please see the attached stacktrace of the full error for more info. Let me know if you need anything else.

[Specs2-Akka--stacktrace.txt](https://github.com/etorreborre/specs2/files/249739/Specs2-Akka--stacktrace.txt)

**Comment by etorreborre** [comment]
I unfortunately don't know exactly how to fix this. Those issues are generally caused by mix-ins and overriding val / methods leading to unexpected results. The best would be to have a small reproducible Github project so that I can see if this is really a specs2 issue or not.

**Comment by djriffel** [comment]
Hi @etorreborre

I made a simplified example project in a public repo so you can take a look.

You can find it here: https://github.com/djriffel/specs2-issue-478

**Comment by etorreborre** [comment]
Thanks for the small project. It seems to be a class loader issue. The Akka system is using a class loader to find its properties. If it is instantiated with `Thread.currentThread.getContextClassLoader` then it can not find its configuration file. If it is instantiated with `getClass.getClassLoader` then it can.

A specification is always instantiated with `Thread.currentThread.getContextClassLoader` and I think this is why there is a problem here. I don't know why but the `Thread.currentThread.getContextClassLoader` contains more information in specs2 `3.7` rather than in `3.8`.

I will try to understand what is going on there.

**Comment by KarelCemus** [comment]
I confirm this issue with Play framework. Same issue but 'play' key is no found in the configuration. Works with 3.7.3, fails with 3.8.

**Comment by etorreborre** [comment]
Thanks again @djriffel for taking the time to prepare a project reproducing the issue (and @KarelCemus for indicating that this was also an issue for Play). The root of the problem is in the context that sbt sets up for a test run. I recently allowed to pass specs2 tags as custom sbt tags but they need to be extracted from the specification. Unfortunately when the tags are being requested there is no proper classloader set-up so Akka properties can not be retrieved. 

This leads to a general recommendation: *never* access any resource inside the body of a specification with `val`. Use `lazy val` instead. This makes it easier to catch exceptions and report them.

The fix is available in `3.8-20160508184712-f62fb45`. I will cut a proper release tomorrow or the day after.
