### ISSUE TITLE
Is the 'rng' parameter to org.specs2.scalacheck.Parameters no longer supported?

### ISSUE THREAD

**Issue by nuttycom** [etorreborre/specs2#494]
In 3.8.4 I can no longer determine how to supply a custom random number generator or custom seed based upon the instructions in https://etorreborre.github.io/specs2/guide/SPECS2-3.8.4/org.specs2.guide.UseScalaCheck.html#test-properties; it looks like it was removed in c6fd12c504381f92172e65297813803d2966f36e - is there a new way to supply a seed?

**Comment by etorreborre** [comment]
If I remember correctly I had to remove that parameter because it is not supported in ScalaCheck 0.13.x which has refactored that part and is supposed to re-introduce a way to control the generation later.

See [here](https://github.com/rickynils/scalacheck/blob/master/src/main/scala/org/scalacheck/Gen.scala#L108) for a nice static call to `Seed.random`.

**Comment by etorreborre** [comment]
I'm closing this for now. I will introduce a seed parameter as soon as it is available in ScalaCheck.
