### ISSUE TITLE
Invalid testcase name in generated JUnit XML

### ISSUE THREAD

**Issue by Pyppe** [etorreborre/specs2#537]
It seems that in certain cases (combination of characters `<`, `.` and `>`) an invalid test-case name is generated in the JUnit XML output.

This is one arbitrary example demonstrating the issue:
```scala
  "This example" should {
    "given <VER.123 FOOBAR> yield <ver.123 foobar>" in {
      ok
    }
  }
```

With this example (using specs2 `3.8.6`) the generated JUnit XML contains the following test-case:
```xml
<testcase classname="org.example.ExampleSpec" name="123 foobar&gt;" time="0.006">
</testcase>
```

Now, obviously the correct XML should be as follows:
```xml
<testcase classname="org.example.ExampleSpec" name="This example should::given &lt;VER.123 FOOBAR&gt; yield &lt;ver.123 foobar&gt;" time="0.006">
</testcase>
```

**Comment by etorreborre** [comment]
I tried a [similar example](https://github.com/etorreborre/specs2/commit/757b8d8ce7d79be710afc0d88ba965fbed9ac9b9) + your test case and everything looks fine on master (which is not very far from `3.8.6`). Since the escaping relies on `scala.xml.Utility.escape` maybe you have an older version of the scala-xml library with a bug in it?

**Comment by Pyppe** [comment]
We use:
```
"org.scala-lang.modules" %% "scala-xml" % "1.0.2"
```

Tried with `1.0.6` (should be the newest) but the issue remained.

**Comment by etorreborre** [comment]
Could you then come up with a minimal github project reproducing the issue?

**Comment by Pyppe** [comment]
I can reproduce it with this simple repo: https://github.com/Pyppe/specs2-junitxml-testcase-name.

Are you seeing the same issue using that setup? Notice, that the issue is also visible without `<` and `>` characters.

**Comment by etorreborre** [comment]
Thanks a lot for the repo. The normal mode of getting junit reports is to add `console junitxml` as arguments:
```scala
testOptions in Test += Tests.Argument("console", "junitxml")
```
You will also need the `specs2-junit` jar on the classpath. 

I those 2 things are left out I think that a junit listener is getting notified and produces the xml file. But I need to check that.

**Comment by Pyppe** [comment]
In our "real repo" we actually do have these:
```
"org.specs2" %% "specs2-junit" % specsVersion
...
Tests.Argument(TestFrameworks.Specs2, "console", "junitxml")
```
Notice the extra first parameter `TestFrameworks.Specs2`. I guess that's (no longer?) needed then. Or maybe it never was. We've been working with this project for several years, so some configuration parameters may have changed along the years. :)

But anyway, in the example repo I tried to do a minimal setup reproducing the behavior.

**Comment by etorreborre** [comment]
The `TestFrameworks.Specs2` argument is necessary to make sure that only specs2 gets it. Otherwise if you also have ScalaTest as a test Framework (`show testFrameworks`) it might get that argument if there is a test class recognized as a ScalaTest one and fail because that argument is unknown to ScalaTest.

Your minimal setup is interesting because it show that something else than specs2 is producing the junit xml output (simply because the specs2-junit jar isn't there) and possibly overwriting specs2 own output when you use `junitxml`. But I don't know yet what.

**Comment by etorreborre** [comment]
Ok, got it: ["By default, sbt will generate JUnit XML test reports for all tests in the build"](http://www.scala-sbt.org/0.13/docs/Testing.html#Test+Reports).

If you want correct names to be generated you can either:

 - create an issue for `sbt` (obviously)
 - disable the junit xml plugin and use the `console junitxml` arguments for specs2 described above

```
disablePlugins(plugins.JUnitXmlReportPlugin)
```

**Comment by Pyppe** [comment]
- Thanks so much @etorreborre for your effort! 🙇
- Created new issue: https://github.com/sbt/sbt/issues/2949
