### ISSUE TITLE
Question regarding DSL

### ISSUE THREAD

**Issue by cmavromoustakos** [etorreborre/specs2#635]
Hello, I am fairly new to Scala and came across this library for validating JSON returned from my API. My JSON structure looks like so:

```json
{"data":{
  "type":"person",
  "id":"e1b1c587-73f3-4d7f-ac1f-4e369bd8d97f",
  "attributes":{ 
    "dateOfDeath":"2018-02-14",
    "dateOfBirth":"2018-02-14",
    "lastName":"Smith",
    "firstName":"John",
     "race":["Caucasian","Black"],
    "isDeceased":false,
    "createdAt":"2018-02-14T16:13:59.646643Z[UTC]",
    "ssn":"123-45-6789"
  }
}}

```

It would be ideal to be able to use something like 

`responseString must /("data")/("attributes")/("race") /# "all" ["Caucasian", "Black"]`

The only way we found to be able to check the array contained in race is:

 ```scala
responseString must /("data")/("attributes")/("race") /# 0 / "Caucasian"
 responseString must /("data")/("attributes")/("race") /# 1 / "Black"
```

We have also tried the following(using the array examples from your documentation) with no success:

```scala

responseString must /("products").andHave(allOf(/("name").andHave(name) and /("price").andHave(price)  and /("ids").andHave(exactly("1", "2", "3") )
responseString must /("data")/("attributes" -> "race") and / ("race" -> contain(List("Caucasian"))
responseString must /("data")/("attributes")/("race" -> ["Caucasian","Black"])
responseString must /("data")/("attributes")/("race") and /("data")/("attributes")/("race").andHave(exactly("Caucasian", "Black"))
responseString must /("data").andHave(/("attributes").andHave(/("race").andHave(exac)))
responseString must /("data") and /("attributes")
```

**Comment by cmavromoustakos** [comment]
This works as well but we want an exact match

```
 responseString must /("data")/("attributes")/("race" -> anyOf("Caucasian", "Black"))
```

**Comment by etorreborre** [comment]
Hi, I cannot give you an answer right now but I will tomorrow morning if you don't mind.

**Comment by etorreborre** [comment]
@cmavromoustakos I think this needs to enter in the category of "internal DSL fails" because this works for me (compiles and gives expected results in case of failure and success):
```
json must (/("data")/"attributes"/"race").andHave(exactly("Caucasian", "Black"))
```
So `andHave` needs to be applied to `(/("data")/"attributes"/"race")` which is a json matcher. We do have to add the parenthesis to make this work. 

Overall I don't find this `JsonMatchers` trait to provide a great DSL for matching JSON data. We are probably better off using a combination of circe lenses to access the data + a simple specs2 matcher to check it. Or just compare JSON outputs as big strings and see the difference in a line by line diff.
