### ISSUE TITLE
JUnit 5?

### ISSUE THREAD

**Issue by mkurz** [etorreborre/specs2#713]
Hello,

is it possible to upgrade to latest JUnit 5.3.1?
https://github.com/etorreborre/specs2/blob/9f93c270421a27bec8001d363f69ca02b5c6fa4f/project/depends.scala#L42

**Comment by etorreborre** [comment]
What would that bring precisely? I am sorry but I haven't been following very closely the developments with JUnit.

**Comment by eyalroth** [comment]
It is impossible to use specs2 in a build that needs JUnit 5 (with the vintage engine). The tests are running _extremely_ slow (profiler says due to reflection "discovery" in the junit engine), and fail with various class-not-found exceptions.

It's more than not supporting JUnit 5's features, but rather this library is _incompatible_ with it. Scalatest for instance, [doesn't support JUnit 5's features either](https://github.com/scalatest/scalatest/issues/1454), but it is compatible with it; i.e, it is possible to use it with the vintage engine.

See my [gradle example project](https://github.com/eyalroth/java-scala-gradle-project) which uses scalatest -- especially the `gradle/test.gradle` and `gradle/scala.gradle` files -- to see how it would be expected to use the library.

**Comment by etorreborre** [comment]
I need to have a look at that again but unfortunately I have very limited time because I'm trying to focus on migrating to Dotty at the moment.

**Comment by etorreborre** [comment]
The latest specs2 on master has now been migrated to `junit-vintage-engine-5.3.2`

**Comment by etorreborre** [comment]
Hmm re-reading the issue, it seems that so work still needs to be done to use the `@ExtendWith` annotation.

**Comment by etorreborre** [comment]
Please check out `specs2-5.0.0-RC-05` which now supports a JUnit 5 `TestEngine` and makes specs2 specifications executable by a JUnit 5 runner without any annotation.
