### ISSUE TITLE
[Feature Request] Have a global Setup and TearDown for whole test Suite to manage expensive resource like containers/db etc

### ISSUE THREAD

**Issue by renjith4** [etorreborre/specs2#737]
It will be good to have a global setup and teardown for whole test suite in addition to the existing setup and teardown for each specification (https://etorreborre.github.io/specs2/guide/SPECS2-2.4.17/org.specs2.guide.Structure.html#Global+setup%2Fteardown). This will be very similar to  @BeforeClass in Junit and will be useful to manage expensive resources like a Db or a testContainer. The approaches that I have seen so far has been by editing build.sbt

- https://github.com/sbt/sbt/issues/2056#issuecomment-387893613
- https://gist.github.com/etorreborre/fb264e72aa4600a6a477

Tinkering with build.sbt doesn't work well with tools, for example IntelliJ which ignores the testOptions in build.sbt

Is there a betterWay to achieve the same, for example from specs2 runner ?

**Comment by etorreborre** [comment]
The only way to achieve this right now I think is to use a [`SpecificationsFinder`](https://github.com/etorreborre/specs2/blob/master/core/shared/src/main/scala/org/specs2/runner/SpecificationsFinder.scala) in a specification where the first `step` is the global init step, then all the found specifications are inserted before one last `step` to shutdown resources.

Otherwise the main difficulty I think is to know when there are no more specifications to execute and when to execute the tear down.

**Comment by etorreborre** [comment]
This is will be available in `specs2-5.0.0`. You can test it in the first release candidate: https://repo1.maven.org/maven2/org/specs2/specs2-core_3/5.0.0-RC-01/. Here is how to use it: https://etorreborre.github.io/specs2/guide/5.0.0-RC-01/org.specs2.guide.Contexts.html#resources
