### ISSUE TITLE
Matchers for http4s Requests and Responses

### ISSUE THREAD

**Issue by thatfulvioguy** [etorreborre/specs2#821]
http4s-testing has recently been deprecated, and it included [some handy matchers for requests and responses](https://github.com/http4s/http4s/blob/master/testing/src/main/scala/org/http4s/testing/Http4sMatchers.scala) that my team liked to use.

Do you reckon these could have new a home within specs2 in a specs2-http4s module? If so, I'd be happy to work on a PR.

**Comment by etorreborre** [comment]
I think it would be better to give it its own repository to help with release / dependencies management. The next major version of specs2 which will fully support Dotty will move some of the modules to separate repositories so that we have a `specs2-core` releasable without any dependencies but the standard lib and other modules which can be released when their dependencies are ready. With the new sbt plugins for managing cascading dependencies this should be hopefully easily automated.

I can create a repository for a `specs2-http4s` module right now, and make you a member if you want to put all that code there.

**Comment by thatfulvioguy** [comment]
Yes, please! That'd be great :)

**Comment by etorreborre** [comment]
Done.
