### ISSUE TITLE
depending on use setMessage does not work

### ISSUE THREAD

**Issue by francisdb** [etorreborre/specs2#832]
specs2 `4.9.4 `

This correctly outputs the message as expected

```scala
statusCode must beEqualTo(OK)
        .setMessage(s"request failed with status $statusCode ${contentAsString(response)}")
```

this one however does not set the message

```scala
(statusCode must be equalTo OK)
        .setMessage(s"request failed with status $statusCode ${contentAsString(response)}")
```

related to https://github.com/etorreborre/specs2/issues/655

**Comment by symbiont-eric-torreborre** [comment]
This is an unfortunate consequence of throwing exceptions in mutable specs by default. I will see if there is a way to fix this but I'm afraid that it might not be possible without some possible API breaks :-(.

**Comment by etorreborre** [comment]
This is an unfortunate consequence of throwing exceptions in mutable specs by default. I will see if there is a way to fix this but I'm afraid that it might not be possible without some possible API breaks :-(.

**Comment by francisdb** [comment]
No worries. At least this ticket can guide the user to a solution :-)

**Comment by etorreborre** [comment]
It is actually fixable for that specific case but harder to do for almost a similar method which is `updateMessage`. I am going to take the conservative approach here and consider that it is better to not complexify or break anything for now.

The fundamental issue is interesting because:
 
 - this is a problem which does not occur when you don't use exceptions
 - this is a problem which can be prevented with laziness. The fact that `(expression returning an object).method()` evaluates the object first in Scala makes it hard to fix the issue

Thanks anyway for reporting this and let's see if we can live with this limitation / inconsistency :-).
