### ISSUE TITLE
Extending both BeforeEach and BeforeAfterEach will run `before` twice

### ISSUE THREAD

**Issue by eyalroth** [etorreborre/specs2#834]
Defining a `before` method in a spec that implements both `BeforeEach` and `BeforeAfterEach` will cause the method to be called **twice** before each test.

```scala
class FooSpec extends Specification with BeforeEach with BeforeAfterEach {

  override def before: Unit = {
    println("this will be printed twice!")
  }

  override def after: Unit = {
    println("this will be printed once, as expected")
  }

  "foo" should {
    "bar" in {
       new Foo().bar() mustEqual true
     }
  }
}
```

If this is not a bug, then this is a major inconvenience, as it is often that some abstract specs extend `BeforeEach`, and other extend `BeforeAfterEach`, and so extending them together will cause `before` do run twice. 

I'd guess this is also the case for `after`, `beforeAll` and `afterAll` with their relevant traits, but I haven't tested this.

**Comment by etorreborre** [comment]
Thanks for the example. I don't know how to better fix this with the current specs2 implementation but this works:
```
class FooSpec extends mutable.Specification with DBSpec with BeforeAfterAll
```
I am going to add a note to the documentation to specify that we can only mix traits like `BeforeXXX` with `BeforeXXX` and as soon as you use `BeforeAfterXXX` you need to mix-in this kind of trait only with another `BeforeAfterXXX`. Otherwise the delegation model in specs2 with add the `before` behaviour for each "level" of the hierarchy: once for `Before`, once for `BeforeAfter`. Unfortunately I don't know how to avoid this. I can also imagine that in some cases people would want the `before` behaviour from 2 different `BeforeXXX` traits to be cumulated.

That's yet another example of why implementation inheritance is hard.

**Comment by eyalroth** [comment]
@etorreborre I understand. In any case, thank you for addressing this :)
