### ISSUE TITLE
Mocking with fs2.Stream as return type fails with WrongTypeOfReturnValue

### ISSUE THREAD

**Issue by randm-ch** [etorreborre/specs2#841]
Hi

I've run into the same problem as described in [this StackOverflow question](https://stackoverflow.com/questions/49070901/mocking-a-method-which-returns-an-fs2-stream) in one of my tests.

```scala
trait MyRepo {
  def readStream: Stream[IO, SomeObject]
}

class MySpec extends Specification with Mockito {
  def is = s2"""
  Something that uses MyRepo should
    be able to return a stream of entitites  $e1
  """

  def e1 = {
    val repo = mock[MyRepo]
    repo.readStream returns fs2.Stream(SomeObject(...)).covary[IO]
    ...
  }
}
```

This produces `org.mockito.exceptions.misusing.WrongTypeOfReturnValue: Stream cannot be returned by readStream(); readStream() should return FreeC`

[mockito-scala](https://github.com/mockito/mockito-scala) fixed the same issue in [this PR](https://github.com/mockito/mockito-scala/pull/62).

**Comment by etorreborre** [comment]
I am sorry but I don't have much time at the moment to investigate this kind of issue. The support for Mockito in specs2 is really hacky and I would indeed recommend you to migrate to mockito-scala if you can. The next major specs2 version is targeting Scala 3 and will drop its mockito module in favour of mockito-scala since it is supporting Scala and Mockito much better.

**Comment by randm-ch** [comment]
No problem, that should work as well. Thanks!
