### ISSUE TITLE
Should I use 4.12.4-js-ec?

### ISSUE THREAD

**Issue by sjmyuan** [etorreborre/specs2#977]
Hi there

I found there is a release `4.12.4-js-ec` in Maven, but can't find it in our release tags, is it a stable version? should I use it?

![image](https://user-images.githubusercontent.com/17628688/130560895-2e8c6b53-adc3-41bf-8974-44072379f922.png)

BTW could I know what `js-ec` means?

**Comment by etorreborre** [comment]
Sorry that was a mistake, you can skip that version. It was a proof of concept to try to run specs2 with another `ExecutionContext` for ScalaJS in order to properly support timeouts. Since then the consensus has been to provide that `ExecutionContext` [as a separate library](https://github.com/scala-js/scala-js/issues/4129) and this will be integrated when available.
